#gcc -o l l.c `pkg-config --cflags --libs glib-2.0`
#INCLS=-I/home/globik/uap-c/include -I/home/globik/uap-c/.build
#LUAP=-L/home/globik/uap-c
l: l.c
	gcc  -o l l.c `pkg-config --cflags --libs glib-2.0`